name: C/C++ CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: make check
      run: make check
