name: C/C++ CI
permissions:
  contents: read

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
    paths-ignore:
      - "doc/**"
      - "CHANGELOG.md"
      - "README.md"
      - ".editorconfig"
      - ".gitignore"
  pull_request:
    branches: [ "*" ]
    paths-ignore:
      - "doc/**"
      - "CHANGELOG.md"
      - "README.md"
      - ".editorconfig"
      - ".gitignore"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            compiler: g++-9
          - os: ubuntu-22.04
            compiler: g++-10
          - os: ubuntu-22.04
            compiler: g++-11
          - os: ubuntu-22.04
            compiler: clang++-14
          - os: ubuntu-22.04
            compiler: clang++-15
          - os: ubuntu-24.04
            compiler: g++-12
          - os: ubuntu-24.04
            compiler: g++-13
          - os: ubuntu-24.04
            compiler: g++-14
          - os: ubuntu-24.04
            compiler: clang++-16
          - os: ubuntu-24.04
            compiler: clang++-17
          - os: ubuntu-24.04
            compiler: clang++-18
          - os: windows-2022
            compiler: default
          - os: macos-latest
            compiler: default
    steps:
    - uses: actions/checkout@v4
    - name: make
      if: runner.os == 'Linux'
      env:
        CXX: ${{ matrix.compiler }}
      run: make -j$(nproc) CI_BUILD=1
    - name: make check
      if: runner.os == 'Linux'
      env:
        CXX: ${{ matrix.compiler }}
      run: make check CI_BUILD=1
    - name: CMake Build (Windows)
      if: runner.os == 'Windows'
      run: |
        cmake -S "${{ github.workspace }}" -B build -G "Visual Studio 17 2022" -DBUILD_TESTS=ON -DBUILD_SAMPLES=ON -DCI_BUILD=ON
        cmake --build build --config Release --target ALL_BUILD
    - name: Run CTest (Windows)
      if: runner.os == 'Windows'
      run: cd build && ctest -C Release -T test --output-on-failure
    - name: Install Ninja (macOS)
      if: runner.os == 'macOS'
      run: brew install ninja
    - name: CMake Build (macOS)
      if: runner.os == 'macOS'
      run: |
        cmake -S "${{ github.workspace }}" -B build -G Ninja -DBUILD_TESTS=ON -DBUILD_SAMPLES=ON -DCI_BUILD=ON
        cmake --build build
    - name: Run CTest (macOS)
      if: runner.os == 'macOS'
      run: cd build && ctest --output-on-failure
