name: C/C++ CI
permissions:
  contents: read

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
    paths-ignore:
      - "doc/**"
      - "*.md"
      - ".editorconfig"
      - ".gitignore"
  pull_request:
    branches: [ "*" ]
    paths-ignore:
      - "doc/**"
      - "*.md"
      - ".editorconfig"
      - ".gitignore"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            compiler: g++-9
            cxxextraflags: "-ftrapv -Wtrampolines"
          - os: ubuntu-22.04
            compiler: g++-10
            cxxextraflags: "-ftrapv -Wtrampolines"
          - os: ubuntu-22.04
            compiler: g++-11
            cxxextraflags: "-ftrapv -Wtrampolines"
          - os: ubuntu-24.04
            compiler: g++-12
            cxxextraflags: "-ftrapv -ftrivial-auto-var-init=pattern -Wbidi-chars=any -Wtrampolines -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3"
          - os: ubuntu-24.04
            compiler: g++-13
            cxxextraflags: "-fstrict-flex-arrays=3 -ftrapv -ftrivial-auto-var-init=pattern -Wbidi-chars=any -Wtrampolines -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3"
          - os: ubuntu-24.04
            compiler: g++-14
            cxxextraflags: "-fhardened -Wno-hardened -fstrict-flex-arrays=3 -ftrapv -ftrivial-auto-var-init=pattern -Wbidi-chars=any -Wtrampolines -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3"
          - os: ubuntu-24.04
            compiler: g++-14
            cxxextraflags: "-fno-exceptions -fno-rtti -fhardened -Wno-hardened -fstrict-flex-arrays=3 -ftrapv -ftrivial-auto-var-init=pattern -Wbidi-chars=any -Wtrampolines -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3"
          - os: ubuntu-22.04
            compiler: clang++-14
            cxxextraflags: "-ftrapv -Wextra-semi-stmt -Wshadow-all -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3"
          - os: ubuntu-22.04
            compiler: clang++-15
            cxxextraflags: "-ftrapv -Wextra-semi-stmt -Wshadow-all -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3"
          - os: ubuntu-24.04
            compiler: clang++-16
            cxxextraflags: "-fstrict-flex-arrays=3 -ftrapv -ftrivial-auto-var-init=pattern -Wextra-semi-stmt -Wshadow-all -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3"
          - os: ubuntu-24.04
            compiler: clang++-17
            cxxextraflags: "-fstrict-flex-arrays=3 -ftrapv -ftrivial-auto-var-init=pattern -Wextra-semi-stmt -Wshadow-all -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3"
          - os: ubuntu-24.04
            compiler: clang++-18
            cxxextraflags: "-fstrict-flex-arrays=3 -ftrapv -ftrivial-auto-var-init=pattern -Wextra-semi-stmt -Wshadow-all -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3"
          - os: ubuntu-24.04
            compiler: clang++-18
            cxxextraflags: "-fno-exceptions -fno-rtti -fstrict-flex-arrays=3 -ftrapv -ftrivial-auto-var-init=pattern -Wextra-semi-stmt -Wshadow-all -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3"
          - os: windows-2022
            compiler: default
          - os: macos-latest
            compiler: default
    steps:
    - uses: actions/checkout@v4
    - name: make
      if: runner.os == 'Linux'
      env:
        CXX: ${{ matrix.compiler }}
      run: make all CI_BUILD=1 CXX=${{ matrix.compiler }} CXXEXTRAFLAGS="${{ matrix.cxxextraflags }}"
    - name: make test
      if: runner.os == 'Linux'
      env:
        CXX: ${{ matrix.compiler }}
      run: make test CI_BUILD=1 CXX=${{ matrix.compiler }} CXXEXTRAFLAGS="${{ matrix.cxxextraflags }}"
    - name: CMake Build (Windows)
      if: runner.os == 'Windows'
      run: |
        cmake -S "${{ github.workspace }}" -B build -G "Visual Studio 17 2022" -DBUILD_TESTS=ON -DBUILD_SAMPLES=ON -DCI_BUILD=ON
        cmake --build build --config Release --target ALL_BUILD
    - name: Run CTest (Windows)
      if: runner.os == 'Windows'
      run: cd build && ctest -C Release -T test --output-on-failure
    - name: Install Ninja (macOS)
      if: runner.os == 'macOS'
      run: brew install --quiet ninja
    - name: CMake Build (macOS)
      if: runner.os == 'macOS'
      run: |
        cmake -S "${{ github.workspace }}" -B build -G Ninja -DBUILD_TESTS=ON -DBUILD_SAMPLES=ON -DCI_BUILD=ON
        cmake --build build
    - name: Run CTest (macOS)
      if: runner.os == 'macOS'
      run: cd build && ctest --output-on-failure
