name: clang-tidy
permissions:
  contents: read

on:
  push:
    branches: [ "master", "develop" ]
    paths:
      - "include/**"
      - "CMakeLists.txt"
      - ".clangtidy"
      - "Makefile"
  pull_request:
    branches: [ "master", "develop" ]
    paths:
      - "include/**"
      - "CMakeLists.txt"
      - ".clangtidy"
      - "Makefile"

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install clang-tidy
      run: |
        sudo apt-get update -yq
        sudo apt-get install -yq clang-tidy
    - name: Run clang-tidy
      run: make lint CI_BUILD=1
