name: clang-analyze
permissions:
  contents: read

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "doc/**"
      - "*.md"
      - ".editorconfig"
      - ".gitignore"
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - "doc/**"
      - "*.md"
      - ".editorconfig"
      - ".gitignore"

jobs:
  clang-analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install clang-tools
      run: |
        sudo apt-get update -yq
        sudo apt-get install -yq clang-tools
    - name: Generating buildsystem
      run: scan-build cmake -S "${{ github.workspace }}" -B build -DBUILD_TESTS=ON -DBUILD_SAMPLES=ON -DCI_BUILD=ON
    - name: Analyzing project
      run: scan-build cmake --build build
